# Heart Disease — Exploratory Data Analysis

**Assignment Task 1 — Data Acquisition & EDA**

This notebook documents the data acquisition, cleaning, and exploratory analysis of the
UCI Heart Disease dataset (Cleveland subset). It reuses the project modules in `src/` so
the exact same logic runs in training, tests, and CI.

Steps:
1. Build the cleaned dataset from the raw UCI files.
2. Inspect structure, missing values, and class balance.
3. Visualize numeric and categorical feature distributions.
4. Examine feature correlations.

In [1]:
import sys
from pathlib import Path

# Make the project root importable when running from notebooks/
ROOT = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
sys.path.insert(0, str(ROOT))

import pandas as pd
from src import config
from src.data_loader import build_dataset, save_processed, load_processed
from src import eda

pd.set_option("display.max_columns", None)

## 1. Build the cleaned dataset

Raw files are header-less and use `?` for missing values. `build_dataset` parses the
Cleveland file, coerces to numeric, drops duplicates, and binarizes the 0–4 severity
target into `{0: no disease, 1: disease}`.

In [2]:
df = build_dataset(sites=["cleveland"])
save_processed(df)
print(df.shape)
df.head()

2026-10-15 01:03:33,947 | INFO | Loaded 303 rows x 14 cols from processed.cleveland.data

2026-10-15 01:03:33,947 | INFO | Combined raw dataset: 303 rows from sites=['cleveland']

2026-10-15 01:03:33,952 | INFO | Cleaned dataset: 303 rows, 6 missing cells, class balance={0: 164, 1: 139}

2026-10-15 01:03:33,955 | INFO | Wrote cleaned dataset -> /Users/auriga/Desktop/new-workspace/task/MLOPS ASSIGNMENT 1/heart-disease-mlops/data/processed/heart.csv

(303, 14)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63.0,1.0,1.0,145.0,233.0,1.0,2.0,150.0,0.0,2.3,3.0,0.0,6.0,0
1,67.0,1.0,4.0,160.0,286.0,0.0,2.0,108.0,1.0,1.5,2.0,3.0,3.0,1
2,67.0,1.0,4.0,120.0,229.0,0.0,2.0,129.0,1.0,2.6,2.0,2.0,7.0,1
3,37.0,1.0,3.0,130.0,250.0,0.0,0.0,187.0,0.0,3.5,3.0,0.0,3.0,0
4,41.0,0.0,2.0,130.0,204.0,0.0,2.0,172.0,0.0,1.4,1.0,0.0,3.0,0

## 2. Structure, missing values, and class balance

In [3]:
df.info()
df.describe().T

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       303 non-null    float64
 1   sex       303 non-null    float64
 2   cp        303 non-null    float64
 3   trestbps  303 non-null    float64
 4   chol      303 non-null    float64
 5   fbs       303 non-null    float64
 6   restecg   303 non-null    float64
 7   thalach   303 non-null    float64
 8   exang     303 non-null    float64
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    float64
 11  ca        299 non-null    float64
 12  thal      301 non-null    float64
 13  target    303 non-null    int64
dtypes: float64(13), int64(1)
memory usage: 33.3 KB

          count        mean        std    min    25%    50%    75%    max
age       303.0   54.438944   9.038662   29.0   48.0   56.0   61.0   77.0
sex       303.0    0.679868   0.467299    0.0    0.0    1.0    1.0    1.0
cp        303.0    3.158416   0.960126    1.0    3.0    3.0    4.0    4.0
trestbps  303.0  131.689769  17.599748   94.0  120.0  130.0  140.0  200.0
chol      303.0  246.693069  51.776918  126.0  211.0  241.0  275.0  564.0
fbs       303.0    0.148515   0.356198    0.0    0.0    0.0    0.0    1.0
restecg   303.0    0.990099   0.994971    0.0    0.0    1.0    2.0    2.0
thalach   303.0  149.607261  22.875003   71.0  133.5  153.0  166.0  202.0
exang     303.0    0.326733   0.469794    0.0    0.0    0.0    1.0    1.0
oldpeak   303.0    1.039604   1.161075    0.0    0.0    0.8    1.6    6.2
slope     303.0    1.600660   0.616226    1.0    1.0    2.0    2.0    3.0
ca        299.0    0.672241   0.937438    0.0    0.0    0.0    1.0    3.0
thal      301.0    4.734219   1.939706    3.0    3.0    3.0    7.0    7.0
target    303.0    0.458746   0.499120    0.0    0.0    0.0    1.0    1.0

In [4]:
print("Missing-value summary:")
display(eda.missing_value_summary(df))
print("\nClass balance:")
display(df[config.TARGET].value_counts().rename({0: "No Disease", 1: "Disease"}))

Missing-value summary:

      missing_count  missing_pct
ca                4         1.32
thal              2         0.66

Class balance:

target
No Disease    164
Disease       139
Name: count, dtype: int64

## 3. Visualizations

All figures are saved to `report/screenshots/` for the report. Run the cells below to
regenerate them.

In [5]:
summary = eda.run_eda()
summary

2026-10-15 01:03:33,994 | INFO | Loaded processed dataset: 303 rows x 14 cols

2026-10-15 01:03:33,995 | INFO | Missing-value summary:
      missing_count  missing_pct
ca                4         1.32
thal              2         0.66

2026-10-15 01:03:34,092 | INFO | Saved plot -> /Users/auriga/Desktop/new-workspace/task/MLOPS ASSIGNMENT 1/heart-disease-mlops/report/screenshots/class_balance.png

2026-10-15 01:03:34,898 | INFO | Saved plot -> /Users/auriga/Desktop/new-workspace/task/MLOPS ASSIGNMENT 1/heart-disease-mlops/report/screenshots/numeric_histograms.png

2026-10-15 01:03:34,934 | INFO | Using categorical units to plot a list of strings that are all parsable as floats or dates. If these strings should be plotted as numbers, cast to the appropriate data type before plotting.

2026-10-15 01:03:34,936 | INFO | Using categorical units to plot a list of strings that are all parsable as floats or dates. If these strings should be plotted as numbers, cast to the appropriate data type before plotting.

2026-10-15 01:03:34,951 | INFO | Using categorical units to plot a list of strings that are all parsable as floats or dates. If these strings should be plotted as numbers, cast to the appropriate data type before plotting.

2026-10-15 01:03:34,953 | INFO | Using categorical units to plot a list of strings that are all parsable as floats or dates. If these strings should be plotted as numbers, cast to the appropriate data type before plotting.

2026-10-15 01:03:34,970 | INFO | Using categorical units to plot a list of strings that are all parsable as floats or dates. If these strings should be plotted as numbers, cast to the appropriate data type before plotting.

2026-10-15 01:03:34,972 | INFO | Using categorical units to plot a list of strings that are all parsable as floats or dates. If these strings should be plotted as numbers, cast to the appropriate data type before plotting.

2026-10-15 01:03:34,987 | INFO | Using categorical units to plot a list of strings that are all parsable as floats or dates. If these strings should be plotted as numbers, cast to the appropriate data type before plotting.

2026-10-15 01:03:34,989 | INFO | Using categorical units to plot a list of strings that are all parsable as floats or dates. If these strings should be plotted as numbers, cast to the appropriate data type before plotting.

2026-10-15 01:03:35,004 | INFO | Using categorical units to plot a list of strings that are all parsable as floats or dates. If these strings should be plotted as numbers, cast to the appropriate data type before plotting.

2026-10-15 01:03:35,006 | INFO | Using categorical units to plot a list of strings that are all parsable as floats or dates. If these strings should be plotted as numbers, cast to the appropriate data type before plotting.

2026-10-15 01:03:35,021 | INFO | Using categorical units to plot a list of strings that are all parsable as floats or dates. If these strings should be plotted as numbers, cast to the appropriate data type before plotting.

2026-10-15 01:03:35,023 | INFO | Using categorical units to plot a list of strings that are all parsable as floats or dates. If these strings should be plotted as numbers, cast to the appropriate data type before plotting.

2026-10-15 01:03:35,039 | INFO | Using categorical units to plot a list of strings that are all parsable as floats or dates. If these strings should be plotted as numbers, cast to the appropriate data type before plotting.

2026-10-15 01:03:35,041 | INFO | Using categorical units to plot a list of strings that are all parsable as floats or dates. If these strings should be plotted as numbers, cast to the appropriate data type before plotting.

2026-10-15 01:03:35,060 | INFO | Using categorical units to plot a list of strings that are all parsable as floats or dates. If these strings should be plotted as numbers, cast to the appropriate data type before plotting.

2026-10-15 01:03:35,062 | INFO | Using categorical units to plot a list of strings that are all parsable as floats or dates. If these strings should be plotted as numbers, cast to the appropriate data type before plotting.

2026-10-15 01:03:35,414 | INFO | Saved plot -> /Users/auriga/Desktop/new-workspace/task/MLOPS ASSIGNMENT 1/heart-disease-mlops/report/screenshots/categorical_distributions.png

2026-10-15 01:03:35,660 | INFO | Saved plot -> /Users/auriga/Desktop/new-workspace/task/MLOPS ASSIGNMENT 1/heart-disease-mlops/report/screenshots/correlation_heatmap.png

2026-10-15 01:03:35,661 | INFO | EDA summary: {'n_rows': 303, 'n_features': 13, 'class_balance': {0: 164, 1: 139}, 'missing_cells': 6}

{'n_rows': 303,
 'n_features': 13,
 'class_balance': {0: 164, 1: 139},
 'missing_cells': 6}

### Class balance
![class balance](../report/screenshots/class_balance.png)

### Numeric feature distributions
![numeric histograms](../report/screenshots/numeric_histograms.png)

### Categorical feature distributions
![categorical distributions](../report/screenshots/categorical_distributions.png)

### Correlation heatmap
![correlation heatmap](../report/screenshots/correlation_heatmap.png)

## 4. Key observations

- **Dataset size:** 303 patients, 13 features + binary target.
- **Class balance:** ~54% no disease / ~46% disease — reasonably balanced, so accuracy is
  a usable metric but we still report precision/recall/ROC-AUC.
- **Missing values:** only a handful of cells in `ca` and `thal`; handled by imputation
  inside the preprocessing pipeline (fit on training folds only to avoid leakage).
- **Correlations:** `cp`, `thalach`, `exang`, `oldpeak`, `ca`, and `thal` show the
  strongest relationships with the target — consistent with clinical expectations.
- **Modeling implication:** a mix of numeric and categorical features means we need
  scaling for numeric columns and one-hot encoding for categoricals, bundled into a single
  reproducible pipeline (next task).